kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-cert-manager-rb
subjects:
  - kind: ServiceAccount
    name: create-cert-manager-sa
    namespace: cp4ba
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-cert-manager-role
