apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: openshift-gitops
  labels:
    group: applications
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  destination:
    namespace: cp4ba
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/kibana/base
    targetRevision: HEAD
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/cp4ba-bd.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
