apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4ba-operator
  namespace: openshift-gitops
  labels:
    group: applications
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: cp4ba-starter
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/cp4ba/operator
    targetRevision: 'HEAD'
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/cp4ba.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
